name: for loop for each type of secret
on:
  workflow_dispatch:

env:
  CLASSIFIED_SECRETS: "SECRET_1,SECRET_3"
  TOP_SECRET_SECRETS: "SECRET_2,SECRET_4"

jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
      - run: |
          node - << EOF >> ./classified-secrets.json
            allSecrets = JSON.parse(process.env.ALL_SECRETS)

            classifiedSecrets = []

            for (secretName of "${{ env.CLASSIFIED_SECRETS }}".split(",")) {
              classifiedSecrets.push({
                secret: secretName,
                classificationLevel: "classified",
                value: allSecrets[secretName]
              })
            }

            for (secretName of "${{ env.TOP_SECRET_SECRETS }}".split(",")) {
              classifiedSecrets.push({
                secret: secretName,
                classificationLevel: "top-secret",
                value: allSecrets[secretName]
              })
            }
            
            console.log(JSON.stringify(classifiedSecrets, null, "  "))

          EOF
        env:
          ALL_SECRETS: ${{ toJson(secrets) }}
      
      - run: cat ./classified-secrets.json
