name: one line per secret
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat << EOF > ./classified-secrets.json
          [
            {
              "secret": "1",
              "classification-level": "classified",
              "value": "${{ secrets.SECRET_1 }}"
            },
            {
              "secret": "2",
              "classification-level": "top-secret",
              "value": "${{ secrets.SECRET_2 }}"
            },
            {
              "secret": "3",
              "classification-level": "classified",
              "value": "${{ secrets.SECRET_3 }}"
            },
            {
              "secret": "4",
              "classification-level": "top-secret",
              "value": "${{ secrets.SECRET_4 }}"
            }
          ]
          EOF

      - run: cat ./classified-secrets.json
